// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI Blog Assistant flow that suggests improvements to blog post content for enhanced readability and SEO.
 *
 * - aiBlogAssistant - A function that handles the blog post improvement process.
 * - AiBlogAssistantInput - The input type for the aiBlogAssistant function.
 * - AiBlogAssistantOutput - The return type for the aiBlogAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiBlogAssistantInputSchema = z.object({
  content: z
    .string()
    .describe('The content of the blog post to be improved.'),
  focusKeyword: z.string().describe('The focus keyword for SEO optimization.'),
  tone: z
    .string()
    .optional()
    .default('professional')
    .describe('The desired tone of the blog post (e.g., professional, friendly, humorous).'),
});
export type AiBlogAssistantInput = z.infer<typeof AiBlogAssistantInputSchema>;

const AiBlogAssistantOutputSchema = z.object({
  improvedContent: z
    .string()
    .describe('The improved content of the blog post with enhanced readability and SEO.'),
  suggestions: z
    .array(z.string())
    .describe('Specific suggestions for improving the blog post.'),
});
export type AiBlogAssistantOutput = z.infer<typeof AiBlogAssistantOutputSchema>;

export async function aiBlogAssistant(input: AiBlogAssistantInput): Promise<AiBlogAssistantOutput> {
  return aiBlogAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiBlogAssistantPrompt',
  input: {schema: AiBlogAssistantInputSchema},
  output: {schema: AiBlogAssistantOutputSchema},
  prompt: `You are an AI Blog Assistant that helps improve blog post content for readability and SEO.

  Instructions:
  1. Enhance readability by simplifying complex sentences and using clear language.
  2. Optimize for SEO by incorporating the focus keyword naturally within the content.
  3. Adjust the tone of the blog post to be {{{tone}}}.
  4. Provide specific suggestions for further improvement.

  Focus Keyword: {{{focusKeyword}}}

  Original Content:
  {{{content}}}

  Improved Content:
  `,config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const aiBlogAssistantFlow = ai.defineFlow(
  {
    name: 'aiBlogAssistantFlow',
    inputSchema: AiBlogAssistantInputSchema,
    outputSchema: AiBlogAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
